export type Project = {
    id: string;
    slug: string;
    title: string;
    description: string;
    kind: string;
    status: string;
    role: string;
    proof: string;
    tech: string[];
    featured: boolean;
    context: string;
    contribution: string;
    architecture: { summary: string; components: { name: string; detail: string }[] };
    decisions: { title: string; description: string }[];
    results: string[];
    limitations: string;
    resourceNote: string;
    github?: string;
    live?: string;
    references: { label: string; href: string }[];
};
